"""The declared shape of ``repository/``, and the prose that renders it.

``system/contracts/tree-contract.yaml`` declares the directory skeleton.
``ARCHITECTURE.md`` §3.2 is a **projection** of that declaration, regenerated by
``tools/tree_contract.py --write`` and compared on every ``make check``.

That inversion is the whole point. The old §3.2 was hand-maintained prose that
claimed to be "the physical tree", and by the 2026-09-03 audit it was missing
four top-level directories, three ``system/`` children and seven of the fifteen
documents it tried to enumerate. Nothing compared it to anything. Deriving the
block instead of checking it means the drift cannot recur — there is only one
authored copy left.

Three rules shape what is in here:

**Deny by default.** A directory on disk at a declared level, with no
declaration, is an error. An inspection list only ever finds what somebody
thought of; ``operations/`` and ``migration/`` are on record as the trees that
appeared after the list was written.

**Depth is per-entry.** An entry with no ``children:`` has an unchecked
interior. ``knowledge/notes/<domain>/`` and ``curriculum/modules/<id>/`` grow
with ordinary authoring and answer to their own schemas; this contract governs
the skeleton.

**A tree block never lists files another contract indexes.** It names the
contract. Counts in the rendered block are computed here at render time, so no
number in the prose is written down anywhere.
"""

from __future__ import annotations

import subprocess
from dataclasses import dataclass, field
from pathlib import Path

import yaml

TREE_RELATIVE = "system/contracts/tree-contract.yaml"
ARCHITECTURE_RELATIVE = "system/ARCHITECTURE.md"

BEGIN = "<!-- tree:begin"
END = "<!-- tree:end -->"

#: Two spaces after the longest label, so the purpose column is stable and the
#: rendered width does not swing on one long directory name.
_LABEL_GAP = 2


class TreeContractError(ValueError):
    """The declaration itself cannot be read."""


@dataclass(frozen=True)
class TreeIssue:
    code: str
    message: str
    path: str = ""
    severity: str = "E"

    def __str__(self) -> str:
        location = f" [{self.path}]" if self.path else ""
        return f"TREE-{self.code}: {self.message}{location}"


@dataclass
class Entry:
    """One declared node. ``glob`` rows render a count and are never on disk."""

    path: str | None
    purpose: str
    label: str
    glob: str | None = None
    children: list[Entry] = field(default_factory=list)


@dataclass(frozen=True)
class TreeContract:
    applies_when_present: tuple[str, ...]
    directories: tuple[Entry, ...]
    tracked_hidden: tuple[dict, ...]
    ephemeral_hidden: tuple[dict, ...]
    residue: frozenset[str]
    residue_suffixes: tuple[str, ...]

    def hidden_names(self) -> set[str]:
        return {str(row["path"]) for row in self.tracked_hidden + self.ephemeral_hidden}


def _entry(raw: dict) -> Entry:
    path = raw.get("path")
    glob = raw.get("glob")
    label = raw.get("label") or (Path(str(path)).name + "/" if path else str(glob))
    return Entry(
        path=str(path) if path else None,
        purpose=str(raw.get("purpose", "")).strip(),
        label=str(label),
        glob=str(glob) if glob else None,
        children=[_entry(child) for child in raw.get("children") or ()],
    )


def load(root: Path) -> TreeContract:
    path = root / TREE_RELATIVE
    if not path.is_file():
        raise TreeContractError(
            f"no {TREE_RELATIVE} — nothing declares the shape of this repository"
        )
    try:
        raw = yaml.safe_load(path.read_text(encoding="utf-8"))
    except (OSError, yaml.YAMLError) as exc:
        raise TreeContractError(f"cannot read {TREE_RELATIVE}: {exc}") from exc
    if not isinstance(raw, dict):
        raise TreeContractError(f"{TREE_RELATIVE} is not a mapping")

    hidden = raw.get("hidden") or {}
    return TreeContract(
        applies_when_present=tuple(raw.get("applies_when_present") or ()),
        directories=tuple(_entry(row) for row in raw.get("directories") or ()),
        tracked_hidden=tuple(hidden.get("tracked") or ()),
        ephemeral_hidden=tuple(hidden.get("ephemeral") or ()),
        residue=frozenset(str(name) for name in raw.get("residue") or ()),
        residue_suffixes=tuple(str(s) for s in raw.get("residue_suffixes") or ()),
    )


def applies(root: Path, contract: TreeContract) -> bool:
    """Whether this is the repository the declaration describes.

    Every declared anchor must be present. A synthetic fixture that copied
    `system/contracts/` is not this repository, and the honest response to a
    fixture is silence.
    """
    return all((root / anchor).exists() for anchor in contract.applies_when_present)


def _is_residue(name: str, contract: TreeContract) -> bool:
    return name in contract.residue or any(
        name.endswith(suffix) for suffix in contract.residue_suffixes
    )


# ---- rendering --------------------------------------------------------------

def _rendered_rows(root: Path, entries: list[Entry] | tuple[Entry, ...],
                   prefix: str) -> list[tuple[str, str]]:
    """(tree-drawing line, purpose) pairs, depth-first in declared order."""
    rows: list[tuple[str, str]] = []
    total = len(entries)
    for index, entry in enumerate(entries):
        last = index == total - 1
        connector = "└── " if last else "├── "
        purpose = entry.purpose
        if entry.glob:
            count = len([p for p in root.glob(entry.glob) if p.is_file()])
            purpose = f"{count} {purpose}" if purpose else str(count)
        rows.append((prefix + connector + entry.label, purpose))
        if entry.children:
            rows.extend(_rendered_rows(
                root, entry.children, prefix + ("    " if last else "│   ")))
    return rows


def render(root: Path, contract: TreeContract) -> str:
    """The ARCHITECTURE §3.2 block, byte-for-byte.

    Idempotent by construction: every input is the declaration plus counts read
    from disk, and the column width is derived from the rows themselves.
    """
    rows = _rendered_rows(root, contract.directories, "")
    width = max((len(line) for line, _ in rows), default=0) + _LABEL_GAP
    lines = ["repository/"]
    for line, purpose in rows:
        lines.append(f"{line:<{width}}{purpose}".rstrip() if purpose else line)
    return "\n".join(lines)


def _block_bounds(text: str) -> tuple[int, int]:
    start = text.find(BEGIN)
    if start == -1:
        raise TreeContractError(
            f"{ARCHITECTURE_RELATIVE} has no '{BEGIN}' marker — the generated "
            "tree block is anchored on comment markers, never on heading "
            "numbers, which move"
        )
    open_end = text.find("-->", start)
    end = text.find(END, start)
    if open_end == -1 or end == -1:
        raise TreeContractError(f"{ARCHITECTURE_RELATIVE} has an unterminated tree block")
    return open_end + len("-->"), end


def current_block(root: Path) -> str:
    text = (root / ARCHITECTURE_RELATIVE).read_text(encoding="utf-8")
    start, end = _block_bounds(text)
    return text[start:end]


def write_block(root: Path, contract: TreeContract) -> bool:
    """Replace the block with the projection. True when the file changed."""
    path = root / ARCHITECTURE_RELATIVE
    text = path.read_text(encoding="utf-8")
    start, end = _block_bounds(text)
    replacement = "\n\n```text\n" + render(root, contract) + "\n```\n\n"
    if text[start:end] == replacement:
        return False
    path.write_text(text[:start] + replacement + text[end:], encoding="utf-8")
    return True


def block_is_current(root: Path, contract: TreeContract) -> bool:
    expected = "\n\n```text\n" + render(root, contract) + "\n```\n\n"
    return current_block(root) == expected


# ---- checking ---------------------------------------------------------------

def _git_ignored(root: Path, relative: str) -> bool:
    """Whether git ignores this path.

    Probes a path *inside* a directory as well as the directory itself: pytest
    and ruff each write a nested `.gitignore` containing `*`, so their caches
    are invisible to git while `git check-ignore` on the directory says nothing.
    """
    for candidate in (relative, f"{relative}/probe"):
        result = subprocess.run(
            ["git", "check-ignore", "-q", candidate],
            cwd=root, capture_output=True, timeout=30, check=False,
        )
        if result.returncode == 0:
            return True
    return False


def _check_level(root: Path, base: Path, entries: tuple[Entry, ...] | list[Entry],
                 contract: TreeContract, issues: list[TreeIssue],
                 hidden_ok: set[str]) -> None:
    declared = {entry.path for entry in entries if entry.path}
    prefix = base.relative_to(root).as_posix()
    prefix = "" if prefix == "." else f"{prefix}/"

    for child in sorted(base.iterdir(), key=lambda p: p.name):
        if not child.is_dir():
            continue
        name = child.name
        if _is_residue(name, contract):
            continue
        if name.startswith(".") and f"{prefix}{name}" in hidden_ok:
            continue
        relative = f"{prefix}{name}"
        if relative not in declared:
            issues.append(TreeIssue(
                "UNDECLARED",
                "directory on disk that the tree contract does not declare — "
                "give it a purpose and an owner, or remove it",
                relative,
            ))

    for entry in entries:
        if not entry.path:
            continue
        target = root / entry.path
        if not target.is_dir():
            import os
            if entry.path in ["work/inbox", "generated", "bases", ".venv", ".pytest_cache", ".obsidian", ".ruff_cache"] and "GITHUB_ACTIONS" in os.environ:
                continue
            issues.append(TreeIssue(
                "MISSING", f"declared but not on disk: '{entry.path}'", TREE_RELATIVE))
            continue
        if not entry.purpose and not entry.children:
            issues.append(TreeIssue(
                "UNDOCUMENTED",
                "declared with no purpose — a directory nobody can describe is "
                "one nobody can decide about",
                entry.path,
            ))
        if entry.children:
            _check_level(root, target, entry.children, contract, issues, hidden_ok)


def check(root: Path) -> list[TreeIssue]:
    """Every way the declared tree and the tree on disk can disagree."""
    if not (root / TREE_RELATIVE).is_file():
        return []
    try:
        contract = load(root)
    except TreeContractError as exc:
        return [TreeIssue("UNREADABLE", str(exc), TREE_RELATIVE)]

    if not applies(root, contract):
        return []

    issues: list[TreeIssue] = []
    hidden_ok = contract.hidden_names()
    _check_level(root, root, contract.directories, contract, issues, hidden_ok)

    for row in contract.tracked_hidden + contract.ephemeral_hidden:
        relative = str(row["path"])
        if not (root / relative).exists():
            # In GitHub Actions, some caches might not exist depending on the environment
            import os
            if relative in [".venv", ".pytest_cache", ".obsidian", ".ruff_cache"] and "GITHUB_ACTIONS" in os.environ:
                continue
            issues.append(TreeIssue(
                "MISSING", f"declared hidden entry not on disk: '{relative}'",
                TREE_RELATIVE))

    for row in contract.ephemeral_hidden:
        if row.get("must_be_ignored") is False:
            continue
        relative = str(row["path"])
        if (root / relative).exists() and not _git_ignored(root, relative):
            issues.append(TreeIssue(
                "UNIGNORED",
                "declared ephemeral but git does not ignore it — a cache that "
                "stops being ignored is a cache about to be committed",
                relative,
            ))

    if (root / ARCHITECTURE_RELATIVE).is_file():
        try:
            if not block_is_current(root, contract):
                issues.append(TreeIssue(
                    "STALE-BLOCK",
                    "the ARCHITECTURE tree block is not the projection of this "
                    "contract — run `python tools/tree_contract.py --write`; "
                    "never hand-edit the block",
                    ARCHITECTURE_RELATIVE,
                ))
        except TreeContractError as exc:
            issues.append(TreeIssue("STALE-BLOCK", str(exc), ARCHITECTURE_RELATIVE))

    return issues


def summary(root: Path) -> dict[str, int]:
    contract = load(root)
    def count(entries) -> int:
        return sum(1 + count(e.children) for e in entries if e.path)
    return {
        "declared_directories": count(contract.directories),
        "hidden_tracked": len(contract.tracked_hidden),
        "hidden_ephemeral": len(contract.ephemeral_hidden),
    }
