import pandas as pd, polars as pl, warnings, inspect
def show(label, fn):
    with warnings.catch_warnings(record=True) as w:
        warnings.simplefilter("always")
        try:
            r = fn(); print(f"--- {label}\n{r}")
        except Exception as e:
            print(f"--- {label}\n    RAISES {type(e).__name__}: {str(e)[:200]}")
        for x in w:
            print(f"    WARN {x.category.__name__}: {str(x.message)[:160]}")
    print()

print("### 1. polars GroupBy.count deprecation?")
d = pl.DataFrame({"g":["a","a"],"x":[1,None]})
show("pl gb.count()", lambda: d.group_by("g").count())
print(inspect.getdoc(pl.dataframe.group_by.GroupBy.count)[:400])

print("\n### 2. quantile interpolation defaults")
print("pandas gb.quantile sig:", inspect.signature(pd.core.groupby.DataFrameGroupBy.quantile))
print("polars gb.quantile sig:", inspect.signature(pl.dataframe.group_by.GroupBy.quantile))
print("pandas Series.quantile sig:", inspect.signature(pd.Series.quantile))
print("polars Series.quantile sig:", inspect.signature(pl.Series.quantile))
s_pd = pd.Series([1,2,3,4]); s_pl = pl.Series([1,2,3,4])
show("pandas s.quantile(.5)", lambda: s_pd.quantile(0.5))
show("polars s.quantile(.5)", lambda: s_pl.quantile(0.5))
show("polars s.quantile(.5,'linear')", lambda: s_pl.quantile(0.5, "linear"))

print("### 3. nunique / n_unique null handling")
show("pandas nunique default", lambda: pd.Series([1,None,1]).nunique())
show("pandas nunique(dropna=False)", lambda: pd.Series([1,None,1]).nunique(dropna=False))
show("polars n_unique", lambda: pl.Series([1,None,1]).n_unique())
print("pandas nunique sig:", inspect.signature(pd.Series.nunique))
print("polars n_unique sig:", inspect.signature(pl.Series.n_unique))
print("pandas gb.nunique sig:", inspect.signature(pd.core.groupby.DataFrameGroupBy.nunique))
print("polars gb.n_unique sig:", inspect.signature(pl.dataframe.group_by.GroupBy.n_unique))
print()

print("### 4. all-null group: sum / min_count")
a_pd = pd.DataFrame({"g":["a","a"],"x":[None,None]})
a_pl = pl.DataFrame({"g":["a","a"],"x":[None,None]}, schema={"g":pl.String,"x":pl.Int64})
show("pandas gb.sum()", lambda: a_pd.groupby("g").sum())
show("pandas gb.sum(min_count=1)", lambda: a_pd.groupby("g").sum(min_count=1))
show("polars gb.sum()", lambda: a_pl.group_by("g").sum())
show("pandas gb.mean()", lambda: a_pd.groupby("g").mean())
show("polars gb.mean()", lambda: a_pl.group_by("g").mean())

print("### 5. dtype promotion on grouped sum with nulls")
n_pd = pd.DataFrame({"g":["a","a"],"x":[1,None]})
n_pl = pl.DataFrame({"g":["a","a"],"x":[1,None]})
show("pandas gb.sum() dtypes", lambda: n_pd.groupby("g").sum().dtypes)
show("polars gb.sum() dtypes", lambda: n_pl.group_by("g").sum().dtypes)
show("pandas gb.count() dtypes", lambda: n_pd.groupby("g").count().dtypes)
show("polars gb.len() dtypes", lambda: n_pl.group_by("g").len().dtypes)

print("### 6. polars gb.agg(bare column string) semantics")
f = pl.DataFrame({"g":["a","a","b"],"x":[1,2,3]})
show("pl gb.agg('x')", lambda: f.group_by("g", maintain_order=True).agg("x"))
show("pl gb.agg(pl.col('x'))", lambda: f.group_by("g", maintain_order=True).agg(pl.col("x")))
show("pd gb.agg('x')?", lambda: pd.DataFrame({"g":["a","a","b"],"x":[1,2,3]}).groupby("g").agg("x"))

print("### 7. non-numeric under grouped reducers")
m_pd = pd.DataFrame({"g":["a","a"],"s":["p","q"],"v":[1,2]})
m_pl = pl.DataFrame({"g":["a","a"],"s":["p","q"],"v":[1,2]})
show("pandas gb.mean() with str", lambda: m_pd.groupby("g").mean())
show("pandas gb.mean(numeric_only=True)", lambda: m_pd.groupby("g").mean(numeric_only=True))
show("polars gb.mean() with str", lambda: m_pl.group_by("g").mean())
show("pandas gb.max() with str", lambda: m_pd.groupby("g").max())
show("polars gb.max() with str", lambda: m_pl.group_by("g").max())

print("### 8. group key column collision / key retained as data")
show("pandas gb.sum() keys in index", lambda: m_pd.groupby("g").sum().index.name)
show("polars gb.sum() key is column", lambda: m_pl.group_by("g").sum().columns)
show("pandas gb.max() includes key col?", lambda: list(m_pd.groupby("g").max().columns))
show("polars gb.max() includes key col?", lambda: m_pl.group_by("g").max().columns)

print("### 9. AGG_FUNCS entrypoint names")
print("pandas DataFrame.agg is aggregate:", pd.DataFrame.agg is pd.DataFrame.aggregate)
print("pandas gb.agg is gb.aggregate:", pd.core.groupby.DataFrameGroupBy.agg is pd.core.groupby.DataFrameGroupBy.aggregate)
print("polars GroupBy has aggregate:", hasattr(pl.dataframe.group_by.GroupBy, "aggregate"))
print("pandas DataFrame.aggregate sig:", inspect.signature(pd.DataFrame.aggregate))
print("pandas Series.aggregate sig:", inspect.signature(pd.Series.aggregate))
print("pandas gb.aggregate sig:", inspect.signature(pd.core.groupby.DataFrameGroupBy.aggregate))
print("pandas SeriesGroupBy.aggregate sig:", inspect.signature(pd.core.groupby.SeriesGroupBy.aggregate))
print("polars GroupBy.agg sig:", inspect.signature(pl.dataframe.group_by.GroupBy.agg))

print("\n### 10. axis=1 on groupby")
show("pandas gb over axis=1?", lambda: pd.DataFrame({"a":[1],"b":[2]}).groupby(level=0, axis=1))
show("pandas df.agg(axis=1) list", lambda: pd.DataFrame({"a":[1,2],"b":[3,4]}).agg(["sum","mean"], axis=1))

print("### 11. observed / categorical groups")
c_pd = pd.DataFrame({"g":pd.Categorical(["a","a"], categories=["a","b"]),"x":[1,2]})
show("pandas observed=True (default 3.x)", lambda: c_pd.groupby("g").sum())
show("pandas observed=False", lambda: c_pd.groupby("g", observed=False).sum())
c_pl = pl.DataFrame({"g":pl.Series(["a","a"],dtype=pl.Enum(["a","b"])),"x":[1,2]})
show("polars enum group_by", lambda: c_pl.group_by("g").sum())
