"""The derived semantic layer (Intelligence Plane, Phase 0).

Phase 1 grows this package toward ~25 predicates plus lineage, goal
detection, task IR, dossier, and proof-carrying-change services. Each of
those arrives as its own module with its own tests; nothing here may become
a canonical writer — see `system/SEMANTIC-CONTRACT.md`.
"""

from __future__ import annotations

from .changes import (
    APPROVER,
    VERDICTS,
    AdmissionDecision,
    ChangeEnvelope,
    ChangeError,
    Postcondition,
    PostconditionResult,
    WriteOp,
    admit,
    build_envelope,
    verify_postconditions,
)
from .dossiers import (
    DEPENDENCIES,
    DOSSIERS_RELATIVE,
    Dossier,
    DossierError,
    build_dossier,
    cache_path,
    compute_hashes,
    is_fresh,
    load_dossier,
    store_dossier,
)
from .goals import (
    AUTHORIZER,
    STATES,
    TERMINAL_STATES,
    TRANSITIONS,
    CandidateGoal,
    GoalError,
    detect_covering_routes_stale,
    detect_inspection_without_dossier,
    detect_repeated_question_gap,
    detect_reviewer_correction_pattern,
    detect_source_changed_under_claim,
    goal_from_dict,
    goal_to_dict,
    transition,
)
from .lineage import (
    ClaimLineage,
    DerivedFrom,
    LineageError,
    contest,
    dump_ledger,
    emit_dossier_freshness,
    emit_route_covers,
    emit_scope_authority,
    endorse,
    impacted,
    load_ledger,
    record_claim,
    refresh,
    retraction_impact,
    withdraw,
)
from .policy import POLICY_RULES, PolicyDecision, query
from .predicates import (
    CONTRACT_VERSION,
    PREDICATES,
    Predicate,
    evaluate,
    needs_study_map,
)
from .tasks import (
    MODEL_ONLY_STEPS,
    STEP_EXECUTORS,
    STEP_KINDS,
    PlannedStep,
    RouterDecision,
    TaskError,
    TaskIR,
    TaskStep,
    plan_task,
    rewrite_cheapest_evidence_first,
    rewrite_dedup,
    rewrite_late_materialization,
    rewrite_pushdown,
    route_step,
    validate_ir,
)

__all__ = [
    "APPROVER",
    "AUTHORIZER",
    "CONTRACT_VERSION",
    "MODEL_ONLY_STEPS",
    "POLICY_RULES",
    "PREDICATES",
    "STATES",
    "STEP_EXECUTORS",
    "STEP_KINDS",
    "TERMINAL_STATES",
    "TRANSITIONS",
    "VERDICTS",
    "AdmissionDecision",
    "CandidateGoal",
    "ChangeEnvelope",
    "ChangeError",
    "ClaimLineage",
    "DEPENDENCIES",
    "DOSSIERS_RELATIVE",
    "DerivedFrom",
    "Dossier",
    "DossierError",
    "GoalError",
    "LineageError",
    "PlannedStep",
    "PolicyDecision",
    "Postcondition",
    "PostconditionResult",
    "Predicate",
    "RouterDecision",
    "TaskError",
    "TaskIR",
    "TaskStep",
    "WriteOp",
    "admit",
    "build_dossier",
    "build_envelope",
    "cache_path",
    "compute_hashes",
    "contest",
    "detect_covering_routes_stale",
    "detect_inspection_without_dossier",
    "detect_repeated_question_gap",
    "detect_reviewer_correction_pattern",
    "detect_source_changed_under_claim",
    "dump_ledger",
    "emit_dossier_freshness",
    "emit_route_covers",
    "emit_scope_authority",
    "endorse",
    "evaluate",
    "goal_from_dict",
    "goal_to_dict",
    "impacted",
    "is_fresh",
    "load_dossier",
    "load_ledger",
    "needs_study_map",
    "plan_task",
    "query",
    "record_claim",
    "refresh",
    "retraction_impact",
    "rewrite_cheapest_evidence_first",
    "rewrite_dedup",
    "rewrite_late_materialization",
    "rewrite_pushdown",
    "route_step",
    "store_dossier",
    "transition",
    "validate_ir",
    "verify_postconditions",
    "withdraw",
]
