#!/usr/bin/env python3
"""Checksummed inventory of the external materials tree.

    python tools/materials_manifest.py --build     # write the manifest
    python tools/materials_manifest.py             # verify (fast: size + presence)
    python tools/materials_manifest.py --deep      # verify (sha256 every file)
    python tools/materials_manifest.py --against /path/to/restored/materials

WHY THIS EXISTS
---------------
``materials/`` lives outside the authored tree by design (CLAUDE.md §11) and is
tracked by no Git repository — it is ~1.9 GB of PDFs, slides and notebooks.
Hundreds of ``material://`` references in canonical records resolve into it.
Before this manifest the repository had no record of what *should* be there, so
it could not tell the difference between three very different situations:

    the drive is unmounted        (recoverable, ignore)
    a file was deliberately moved (update the inventory)
    a file is silently gone       (data loss — the reference is now a lie)

The manifest is the repository's own durable record of the external tree, so
those cases become distinguishable and a restored backup can be *proved*
complete and uncorrupted with ``--against``.

WHAT IS EXCLUDED
----------------
Symlinks (the ``.flat/`` URI-compat farm points back into the same tree),
``.DS_Store``, the three artifacts ``tools/build_materials_index.py``
regenerates (``README.md``, ``FILES.txt``, ``INDEX.html``), and the per-folder
``SOURCES.md`` files ``tools/build_materials_tree.py`` rewrites — derived data
is reproducible and would drift the manifest on every ``make materials``.
"""

from __future__ import annotations

import argparse
import datetime as _dt
import hashlib
import sys
from pathlib import Path

import yaml

ROOT = Path(__file__).resolve().parent.parent
MANIFEST = ROOT / "records" / "materials-manifest.yaml"
SCHEMA_VERSION = 1

#: Regenerated by tools/build_materials_index.py — derived, not durable.
GENERATED_AT_ROOT = frozenset({"README.md", "FILES.txt", "INDEX.html"})
#: Regenerated per folder by tools/build_materials_tree.py at any depth, so the
#: manifest would otherwise drift on every `make materials`.
GENERATED_ANYWHERE = frozenset({"SOURCES.md"})
SKIP_NAMES = frozenset({".DS_Store"})

_HEADER = """\
# Generated — do not hand-edit. Rebuild with:
#     python tools/materials_manifest.py --build
#
# The repository's durable record of the external materials/ tree, which is
# tracked by no Git repository. `make check` uses it to tell "the drive is
# offline" apart from "a referenced file is actually gone", and
# `--against <path>` uses it to prove a restored backup is complete.
#
# Excludes symlinks (.flat/), .DS_Store, the generated catalogue
# (README.md, FILES.txt, INDEX.html) and the per-folder SOURCES.md indexes.
"""


def materials_root(root: Path = ROOT) -> Path:
    """``materials/`` sits beside the repository, under the LearningOS root."""
    return root.parent / "materials"


def iter_material_files(base: Path):
    """Yield (relative_posix_path, absolute_path) for every durable file."""
    if not base.is_dir():
        return
    for path in sorted(base.rglob("*")):
        if path.is_symlink() or not path.is_file():
            continue
        if path.name in SKIP_NAMES or path.name in GENERATED_ANYWHERE:
            continue
        rel = path.relative_to(base)
        if len(rel.parts) == 1 and rel.name in GENERATED_AT_ROOT:
            continue
        yield rel.as_posix(), path


def sha256(path: Path, chunk: int = 1 << 20) -> str:
    digest = hashlib.sha256()
    with path.open("rb") as handle:
        while block := handle.read(chunk):
            digest.update(block)
    return digest.hexdigest()


def build(base: Path) -> dict:
    files: dict[str, dict] = {}
    total = 0
    for rel, path in iter_material_files(base):
        size = path.stat().st_size
        files[rel] = {"size": size, "sha256": sha256(path)}
        total += size
    return {
        "schema_version": SCHEMA_VERSION,
        "captured": _dt.date.today().isoformat(),
        "totals": {"files": len(files), "bytes": total},
        "files": files,
    }


def load_manifest(path: Path = MANIFEST) -> dict | None:
    if not path.exists():
        return None
    return yaml.safe_load(path.read_text(encoding="utf-8"))


def verify(manifest: dict, base: Path, deep: bool = False) -> dict:
    """Compare a materials tree against the manifest.

    Returns {missing, changed, unregistered} — all sorted lists of paths.
    ``changed`` compares size always, and sha256 additionally when *deep*.
    """
    recorded = manifest.get("files") or {}
    present = dict(iter_material_files(base))

    missing = sorted(set(recorded) - set(present))
    unregistered = sorted(set(present) - set(recorded))
    changed = []
    for rel in sorted(set(recorded) & set(present)):
        want, path = recorded[rel], present[rel]
        if path.stat().st_size != want.get("size"):
            changed.append(rel)
        elif deep and sha256(path) != want.get("sha256"):
            changed.append(rel)
    return {"missing": missing, "changed": changed, "unregistered": unregistered}


def _report(result: dict, base: Path, deep: bool) -> int:
    tiers = (("missing", "recorded but NOT PRESENT"),
             ("changed", "content differs from the manifest"),
             ("unregistered", "present but not in the manifest"))
    worst = 0
    for key, blurb in tiers:
        rows = result[key]
        if not rows:
            continue
        worst = max(worst, 1 if key != "unregistered" else 0)
        print(f"\n{len(rows)} file(s) {blurb}:")
        for rel in rows[:20]:
            print(f"  {rel}")
        if len(rows) > 20:
            print(f"  … and {len(rows) - 20} more")
    if not any(result[k] for k, _ in tiers):
        print(f"OK — {base} matches the manifest"
              f"{' (sha256 verified)' if deep else ' (size + presence)'}")
    return worst


def main() -> int:
    parser = argparse.ArgumentParser(description=__doc__,
                                     formatter_class=argparse.RawDescriptionHelpFormatter)
    parser.add_argument("--build", action="store_true",
                        help="rebuild the manifest from the current tree")
    parser.add_argument("--deep", action="store_true",
                        help="verify sha256 of every file, not just size")
    parser.add_argument("--against", default=None, metavar="PATH",
                        help="verify a restored copy at PATH instead of the live tree")
    args = parser.parse_args()

    base = Path(args.against).resolve() if args.against else materials_root()

    if args.build:
        if not base.is_dir():
            print(f"materials tree not found: {base}", file=sys.stderr)
            return 2
        manifest = build(base)
        MANIFEST.parent.mkdir(parents=True, exist_ok=True)
        MANIFEST.write_text(
            _HEADER + yaml.safe_dump(manifest, sort_keys=False, allow_unicode=True),
            encoding="utf-8")
        gb = manifest["totals"]["bytes"] / 1024**3
        print(f"wrote {MANIFEST.relative_to(ROOT)}: "
              f"{manifest['totals']['files']} files, {gb:.2f} GB")
        return 0

    manifest = load_manifest()
    if manifest is None:
        print(f"no manifest at {MANIFEST.relative_to(ROOT)} — "
              "run with --build first", file=sys.stderr)
        return 2
    if not base.is_dir():
        print(f"materials tree not found: {base}\n"
              "Nothing was checked. If the drive is simply unmounted this is "
              "not data loss; the manifest still records what belongs there.",
              file=sys.stderr)
        return 2

    print(f"manifest captured {manifest.get('captured')} — "
          f"{manifest.get('totals', {}).get('files')} files")
    return _report(verify(manifest, base, deep=args.deep), base, args.deep)


if __name__ == "__main__":
    raise SystemExit(main())
